version: '3.x'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin-igpu
    environment:
        - UID=1026
        - GID=100
        - TZ=Asia/Seoul
        - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    network_mode: 'host'
    ports:
      - 8096:8096
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /volume1/_DRAMA:/volume1/_DRAMA
      - /usr/lib/jellyfin-ffmpeg:/ffmpeg
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    privileged: true
    restart: always
